language: cpp
before_script:
 - sudo apt-get install libboost-test-dev -y
script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test
 - cmake --build . --target package
 - ls -l | grep homework*
deploy:
 provider: script
 skip_cleaning: true
 script:
 - curl -T homework_1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ancord-m:$BINTRAY_API_KEY "https://api.bintray.com/content/ancord-m/otus-cpp-hw/hw1/$TRAVIS_BUILD_NUMBER/homework_1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb-distribution=trusty;deb-component=main;deb-architecture=amd64;publish=1"
